name: mirror-to-gitee

on:
    push:
    pull_request_target:
        branches: [master]
    workflow_dispatch:

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v2
    - name: Mirror the Github organization repos to Gitee.
      uses: Yikun/hub-mirror-action@v1.2
      with:
        src: github/xuruizhi
        dst: gitee/xuruizhi
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        white_list: github-action-test
